language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python -m pytest  # Запуск тестов

cache:
  directories:
    - $HOME/.cache/pip

notifications:
  email:
    recipients:
      - birner.vad@gmail.com  # уведомление на почту о статусе сборки
    on_success: always  # Уведомления при успешной сборке
    on_failure: always  # Уведомления при неудачной сборке